export default [
  {
    vote_count: 0,
    id: 573864,
    video: false,
    vote_average: 0,
    title: "Pavilions",
    popularity: 0,
    poster_path: "/g9mNYIHsjM0jZ3As2I405YNh3WN.jpg",
    original_language: "sr",
    original_title: "Paviljoni",
    genre_ids: [18, 10770],
    backdrop_path: null,
    adult: false,
    overview:
      "Three generations - three different microcosms - are entangled in circle. They were all looking for love but ended up experiencing aggression and escape from reality.",
    release_date: "2018-08-20"
  },
  {
    vote_count: 0,
    id: 573862,
    video: false,
    vote_average: 0,
    title: "Silver Strand",
    popularity: 0,
    poster_path: null,
    original_language: "en",
    original_title: "Silver Strand",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "The U.S. Navy selects from its ranks a small group of persons to send through unadulterated hell.",
    release_date: ""
  },
  {
    vote_count: 0,
    id: 573860,
    video: false,
    vote_average: 0,
    title: "I Want to Get Into the Movies!",
    popularity: 0,
    poster_path: "/zoeb8wxb2w4OsMxChYGibMTwYMl.jpg",
    original_language: "en",
    original_title: "I Want to Get Into the Movies!",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "A cube-shaped creature who can’t get into a cinema only equipped to cater to sphere-shaped patrons he wants to check out that awesome triple feature of The Sound of Music, Driving Miss Daisy and Total Recall",
    release_date: ""
  },
  {
    vote_count: 0,
    id: 573859,
    video: false,
    vote_average: 0,
    title: "Dearest Anita",
    popularity: 0,
    poster_path: null,
    original_language: "zh",
    original_title: "Dearest Anita",
    genre_ids: [99, 18, 10402, 36],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: "2019-01-03"
  },
  {
    vote_count: 0,
    id: 573858,
    video: false,
    vote_average: 0,
    title: "Ciemno, prawie noc",
    popularity: 0,
    poster_path: null,
    original_language: "pl",
    original_title: "Ciemno, prawie noc",
    genre_ids: [80, 18],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: "2019-03-22"
  },
  {
    vote_count: 0,
    id: 573857,
    video: false,
    vote_average: 0,
    title: "Al eeteraf al akhir",
    popularity: 0,
    poster_path: "/5Dzp0u0nKgjd8pbnq3bH63jkQfS.jpg",
    original_language: "ar",
    original_title: "الإعتراف الأخير",
    genre_ids: [18],
    backdrop_path: null,
    adult: false,
    overview:
      "Adham a faithful husband still mourning his deceased wife,visited one night by a woman in white revealing her secret love for him since college,and his wife true acts behind his back,but the big revelation was this woman is no longer from the living and its her ghost that paid him a visit.",
    release_date: "1978-05-15"
  },
  {
    vote_count: 0,
    id: 573856,
    video: false,
    vote_average: 0,
    title: "Saugandh",
    popularity: 0,
    poster_path: "/3EAUTCoTTvXoRuZCcI3xDLwsNmM.jpg",
    original_language: "hi",
    original_title: "Saugandh",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "A father worries for his younger son and asks his elder son to promise that he will do everthing in his power to ensure Arun does not go astray, educates himself and becomes an independent man. However, fate has other plans. When Arun commits an unthinkable crime, his brother fulfills the promise made to their father and shields his younger sibling from all harm.",
    release_date: "1942-03-24"
  },
  {
    vote_count: 0,
    id: 573855,
    video: false,
    vote_average: 0,
    title: "Мурзилка и Великан",
    popularity: 0,
    poster_path: "/3jQxzkAwks3gLUhLPqMSJSOHwE7.jpg",
    original_language: "ru",
    original_title: "Мурзилка и Великан",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: "1960-01-01"
  },
  {
    vote_count: 0,
    id: 573854,
    video: false,
    vote_average: 0,
    title: "Parable Of The Blind",
    popularity: 0,
    poster_path: "/zHXfFHWca9qbWfak2zCqCKKyLmq.jpg",
    original_language: "ru",
    original_title: "Притча о слепых",
    genre_ids: [16],
    backdrop_path: "/urLsfk1RHwS2fOQTSW4kVYhy7SI.jpg",
    adult: false,
    overview:
      "The action takes place on the stage of a poor theater. The main hero (the buffoon) is jealous of the king of the stage and, sinking into the depths of his mental oppression, kills him. But what exactly does the main hero do? Is he eliminating a competitor or getting closer to the ceremony of his own funeral?",
    release_date: "2018-03-16"
  },
  {
    vote_count: 0,
    id: 573851,
    video: false,
    vote_average: 0,
    title: "The Third Contest",
    popularity: 0,
    poster_path: null,
    original_language: "ja",
    original_title: "Mondonosuke Sanban Shobu",
    genre_ids: [28, 18],
    backdrop_path: null,
    adult: false,
    overview:
      "Mondonosuke, a young sword student, has a bad dream about his sensei being killed in a duel.Consequently, he quickly returns to his sensei's dojo in Edo, where he has not set foot in three years.",
    release_date: "1965-03-07"
  },
  {
    vote_count: 0,
    id: 573847,
    video: false,
    vote_average: 0,
    title: "Neko Kafe",
    popularity: 0,
    poster_path: null,
    original_language: "fr",
    original_title: "Neko Kafe",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: ""
  },
  {
    vote_count: 0,
    id: 573846,
    video: false,
    vote_average: 0,
    title: "Приключения Мурзилки",
    popularity: 0,
    poster_path: "/3qosSVeh1wX46O0GBSQfosQmwmT.jpg",
    original_language: "ru",
    original_title: "Приключения Мурзилки",
    genre_ids: [16],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: "1956-10-09"
  },
  {
    vote_count: 0,
    id: 573845,
    video: false,
    vote_average: 0,
    title: "Cucli",
    popularity: 0,
    poster_path: "/mA9kgL4f7BmIHqH2md89Bw0AB0e.jpg",
    original_language: "en",
    original_title: "Cucli",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "Ramon lives with his parents, although he is away most of the week working as a truck driver. These are long and lonely trips, until he meets a very special companion that changes everything. Cucli tells a story about love and companionship after death, and its transformative effect. A story about how, through memories, the supernatural can find its way into our mundane lives.",
    release_date: "2016-11-24"
  },
  {
    vote_count: 0,
    id: 573844,
    video: false,
    vote_average: 0,
    title: "Eiga : Tôken ranbu",
    popularity: 0,
    poster_path: null,
    original_language: "fr",
    original_title: "Eiga : Tôken ranbu",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: ""
  },
  {
    vote_count: 0,
    id: 573843,
    video: false,
    vote_average: 0,
    title: "The Dreamer",
    popularity: 0,
    poster_path: "/a5Wf5UEWb6p8jh2rRdvY6tQgmLR.jpg",
    original_language: "en",
    original_title: "The Dreamer",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "A man gives up everything to pursue his dreams, only to realize he probably shouldn't have done that.",
    release_date: "2018-07-18"
  },
  {
    vote_count: 0,
    id: 573842,
    video: false,
    vote_average: 0,
    title: "Nartaki",
    popularity: 0,
    poster_path: "/ziwKLnHjhz63VedwlNRzZukAWld.jpg",
    original_language: "hi",
    original_title: "Nartaki",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview:
      "Roopkumari (Leela Desai) a famous court dancer is forbidden entry into a temple monastery run by a strict disciplinarian Priest. The cast listed here is for the Hindi version, there is also a Bengali version with a different cast, but same director and release year.",
    release_date: "1940-12-18"
  },
  {
    vote_count: 0,
    id: 573841,
    video: false,
    vote_average: 0,
    title: "New Tale of the Genji",
    popularity: 0,
    poster_path: "/6CTz3NXirXSPw2TnhsfLv0chuW5.jpg",
    original_language: "ja",
    original_title: "Shin Genji monogatari",
    genre_ids: [18, 10749],
    backdrop_path: null,
    adult: false,
    overview:
      "Hikaru Genji, the haunted romantic hero of Lady Murasaki Shikibu’s “Genji Monogatari” (Tale of Genji) comes to life in this new tale of his further romantic adventures. Young Genji, the emperor’s illegitimate son cuts a swath through the women of the imperial court, while still mourning the spirit of his late mother who died while he was still a child. Driven to an obsession with the emperor’s new concubine, Lady Fujitsubo, whose resemblance to his late mother originally caught the eye of the emperor, young Genji embarks upon a reckless affair with her that could cost him his life.",
    release_date: "1961-10-14"
  },
  {
    vote_count: 0,
    id: 573840,
    video: false,
    vote_average: 0,
    title: "Eugene Atget: Photographer",
    popularity: 0,
    poster_path: null,
    original_language: "en",
    original_title: "Eugene Atget: Photographer",
    genre_ids: [99],
    backdrop_path: null,
    adult: false,
    overview:
      "Meet France’s mysterious master of photography, neglected in his own lifetime but since feted for helping position the medium as an art form, and as an inspiration to surrealists. This meditative Arts Council documentary introduces Eugène Atget, a former actor who began to document the streets of old Paris from the 1890s. Little is known about his early life and the three decades he spent capturing, in eerie tableaux, urban spaces since lost to progress. The film includes dramatised scenes from his life, including his belated ‘discovery’ by American photographers Man Ray and Berenice Abbott, who published many of Atget’s works after his death in 1927.",
    release_date: "1982-01-01"
  },
  {
    vote_count: 0,
    id: 573839,
    video: false,
    vote_average: 0,
    title: "Mid80s",
    popularity: 0,
    poster_path: null,
    original_language: "en",
    original_title: "Mid80s",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview: "Stevie travels back in time for yet more crazy adventures.",
    release_date: ""
  },
  {
    vote_count: 0,
    id: 573838,
    video: false,
    vote_average: 0,
    title: "Uomini e briganti",
    popularity: 0,
    poster_path: null,
    original_language: "it",
    original_title: "Uomini e briganti",
    genre_ids: [],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: "2004-01-01"
  }
];
